---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.8"}

inputs:
- name: source-code

run:
  path: ci/scripts/run-build.sh
  dir: source-code

outputs:
- name: artifact
