---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.8"}

inputs:
- name: source-code
- name: version
- name: artifact

outputs:
  - name: artifacts

run:
  path: source-code/ci/scripts/create-artifacts.sh
